biblioteca/biblioteca/urls.py
from django.contrib import admin
from django.urls import path, include
from libreria import views as libreria_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('libreria.urls')),  
]

biblioteca/libreria/urls.py
from django.urls import path
from . import views

app_name = 'libreria'

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('agregar_autor_libro/', views.agregar_autor_libro, name='agregar_autor_libro'),
    path('buscar_libro/', views.buscar_libro_view, name='buscar_libro'),
    path('agregar_cliente/', views.agregar_cliente, name='agregar_cliente'),
    path('reviews/', views.reviews, name='reviews'),
]

biblioteca/libreria/models.py
from django.db import models

class Autor(models.Model):
    nombre = models.CharField(max_length=100)
    fecha_nacimiento = models.DateField()

    def __str__(self):
        return self.nombre

class Libro(models.Model):
    titulo = models.CharField(max_length=200)
    autor = models.ForeignKey(Autor, on_delete=models.CASCADE)
    fecha_publicacion = models.DateField()
    isbn = models.CharField(max_length=13, unique=True)

    def __str__(self):
        return self.titulo

from django.db import models

class Cliente(models.Model):
    nombre = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    direccion = models.TextField()

    def __str__(self):
        return self.nombre

class Review(models.Model):
    libro = models.ForeignKey(Libro, on_delete=models.CASCADE)
    usuario = models.CharField(max_length=100)
    comentario = models.TextField()
    calificacion = models.IntegerField()

    def __str__(self):
        return f"{self.usuario} - {self.libro}"

biblioteca/libreria/forms.py
from django import forms
from .models import *

class CustomDateInput(forms.DateInput):
    input_type = 'text'

class LibroForm(forms.ModelForm):
    class Meta:
        model = Libro
        fields = ['titulo', 'fecha_publicacion', 'isbn']
        widgets = {
            'fecha_publicacion': CustomDateInput(),
        }

class AutorForm(forms.ModelForm):
    class Meta:
        model = Autor
        fields = ['nombre', 'fecha_nacimiento']
        widgets = {
            'fecha_nacimiento': CustomDateInput(),
        }

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nombre', 'email', 'direccion']

class ReviewsForm(forms.ModelForm):
    class Meta:
        model = Review 
        fields = ['libro', 'usuario', 'comentario', 'calificacion']


biblioteca/libreria/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import *
from .forms import *
from django.core.exceptions import PermissionDenied


def home(request):
    libros = []
    context = {"libros": libros}
    return render(request, 'libreria/home.html', context)

def index(request):
    return render(request, 'libreria/index.html')

def buscar_libro_view(request):
    libros = []
    if 'q' in request.GET:
        query = request.GET['q']
        libros = Libro.objects.filter(titulo__icontains=query)
    return render(request, 'libreria/buscar_libro.html', {'libros': libros})

def lista_libros(request):
    libros = Libro.objects.all()
    context = {
        'libros': libros
    }
    return render(request, 'libreria/lista_libros', context)

def is_admin(user):
    if not user.is_superuser:
        raise PermissionDenied
    return True

def agregar_autor_libro(request):
    if request.method == 'POST':
        autor_form = AutorForm(request.POST, prefix='autor')
        libro_form = LibroForm(request.POST, prefix='libro')
        
        if autor_form.is_valid() and libro_form.is_valid():
            autor = autor_form.save()
            libro = libro_form.save(commit=False)
            libro.autor = autor
            libro.save()
            return redirect('home')
    else:
        autor_form = AutorForm(prefix='autor')
        libro_form = LibroForm(prefix='libro')
    
    return render(request, 'libreria/agregar_autor_libro.html', {
        'autor_form': autor_form,
        'libro_form': libro_form,
    })

def agregar_cliente(request):
    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('libreria:agregar_cliente')
    else:
        form = ClienteForm()

    clientes = Cliente.objects.all()

    return render(request, 'libreria/agregar_cliente.html', {'form': form, 'clientes': clientes})


def reviews(request):
    reviews = Review.objects.all()
    if request.method == 'POST':
        form = ReviewsForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('libreria/reviews.html')
    else:
        form = ReviewsForm()
    return render(request, 'libreria/reviews.html', {'form': form, 'reviews': reviews})


biblioteca/libreria/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>InkSpot</title>
    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}">
    <!-- Bootstrap icons -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet">
    <!-- Core theme CSS (includes Bootstrap) -->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
</head>
<body>
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'libreria:home' %}">InkSpot</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'libreria:buscar_libro' %}">Buscar</a></li>
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'libreria:reviews' %}">Reseñas</a></li>
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'libreria:agregar_autor_libro' %}">Nuevo libro</a></li>
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'libreria:agregar_cliente' %}">Nuevo cliente</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Filtrar</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#!">Todos</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#!">Populares</a></li>
                        <li><a class="dropdown-item" href="#!">Nuevos</a></li>
                    </ul>
                </li>
            </ul>
            <form class="d-flex">
                <button class="btn btn-outline-dark" type="submit">
                    <i class="bi-cart-fill me-1"></i>Carrito
                    <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                </button>
            </form>
        </div>
    </div>
</nav>
<!-- Header -->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">El mejor lugar para vos</h1>
            <p class="lead fw-normal text-white-50 mb-0">Encontra tus libros favoritos</p>
        </div>
    </div>
</header>
    </div>
        </div> 
            </div>

<div class="container">
    {% block content %}



    {% endblock %}
</div>

<!-- Footer -->
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">© 2024 InkSpot</p>
    </div>
</footer>

<!-- Bootstrap core JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS -->
<script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>


biblioteca/libreria/templates/libreria/agregar_autor_libro.html
{% extends 'base.html' %}
{% load static%}

{% block content %}
<h1>Agregar nuevo libro</h1>
<form method="post">
    {% csrf_token %}
    
    <h2>Nombre del libro</h2>
    {{ libro_form.as_p }}

    <h2>Autor</h2>
    {{ autor_form.as_p }}
    
    <button type="submit">Guardar</button>
</form>
{% endblock content%}

biblioteca/libreria/templates/libreria/agregar_cliente.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h2>Agregar Cliente</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Agregar Cliente</button>
    </form>

    <hr>

    <h2>Listado de Clientes</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Email</th>
                <th>Dirección</th>
            </tr>
        </thead>
        <tbody>
            {% for cliente in clientes %}
            <tr>
                <td>{{ cliente.nombre }}</td>
                <td>{{ cliente.email }}</td>
                <td>{{ cliente.direccion }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="3">No hay clientes registrados.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

biblioteca/libreria/templates/libreria/buscar_libro.html
{% extends 'base.html' %}

{% block content %}
<h2>Buscar Libro</h2>
<form method="GET" action="{% url 'libreria:buscar_libro' %}">
    <input type="text" name="q" placeholder="Buscar libro...">
    <button type="submit">Buscar</button>
</form>

{% if libros %}
    <ul>
        {% for libro in libros %}
            <li>{{ libro.titulo }}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>No se encontraron libros.</p>
{% endif %}
{% endblock %}

biblioteca/libreria/templates/libreria/home.html
{% extends 'base.html' %}
{%load static%}

{% block title %}
    <title>Inicio - InkSpot</title>
     </div>
        </div>
{% endblock title%}





{% block content %}
    <!-- Header-->
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">InkSpot</h1>
                <p class="lead fw-normal text-white-50 mb-0">Cualquier libro al alcance de tus manos</p>
            </div>
        </div>
    </header>
    <!-- Section-->
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                {% for product in products %}
                <div class="col mb-5">
                    <div class="card h-100">
                        {% if product.on_sale %}
                        <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Oferta</div>
                        {% endif %}
                        <img class="card-img-top" src="{{ product.image }}" alt="Imagen del producto">
                        <div class="card-body p-4">
                            <div class="text-center">
                                <h5 class="fw-bolder">{{ product.name }}</h5>
                                {% if product.discounted_price %}
                                <span class="text-muted text-decoration-line-through">{{ product.original_price }}</span>
                                {{ product.discounted_price }}
                                {% else %}
                                {{ product.price }}
                                {% endif %}
                            </div>
                        </div>
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center">
                                <a class="btn btn-outline-dark mt-auto" href="{% url 'libreria:agregar_libro' %}">Comprar</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    {% endblock %}

biblioteca/libreria/templates/libreria/login.html
{% extends 'base.html' %}
{%load static%}

{% block title %}
    <title>Inicio - InkSpot</title>
{% endblock %}

{% block content %}
    <!-- Header-->
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder"></h1>
                <p class="lead fw-normal text-white-50 mb-0">Cualquier libro al alcance de tus manos</p>
            </div>
        </div>
    </header>
    <!-- Section-->
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                {% for product in products %}
                <div class="col mb-5">
                    <div class="card h-100">
                        {% if product.on_sale %}
                        <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Oferta</div>
                        {% endif %}
                        <img class="card-img-top" src="{{ product.image }}" alt="Imagen del producto">
                        <div class="card-body p-4">
                            <div class="text-center">
                                <h5 class="fw-bolder">{{ product.name }}</h5>
                                {% if product.discounted_price %}
                                <span class="text-muted text-decoration-line-through">{{ product.original_price }}</span>
                                {{ product.discounted_price }}
                                {% else %}
                                {{ product.price }}
                                {% endif %}
                            </div>
                        </div>
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center">
                                <a class="btn btn-outline-dark mt-auto" href="{% url 'libreria:agregar_libro' %}">Comprar</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    {% endblock %}

biblioteca/libreria/templates/libreria/reviews.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h2>Reseñas</h2>

    <div class="reseñas-list">
        {% for review in reviews %}
            <div class="reseña">
                <h4>{{ review.usuario }} - {{ review.libro.titulo }}</h4>
                <p>{{ review.comentario }}</p>
                <p>Calificación: {{ review.calificacion }}</p>
            </div>
        {% empty %}
            <p>No hay reseñas aún.</p>
        {% endfor %}
    </div>

    <div class="agregar-reseña">
        <h3>Agregar Reseña</h3>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Agregar Reseña</button>
        </form>
    </div>
</div>
{% endblock %}